server:
  port: 9001
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

spring:
  datasource:
    username: developer
    password: p4SSW0rd
    url: jdbc:postgresql://localhost:5432/demo
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      pool-name: polardb-pool

  jpa:
    hibernate:
      ddl-auto: create-drop
